### PR TITLE
Issue resolved #117

### LINKED ISSUE #117: Makefiles don’t work on macOS
**Describe the bug**
Makefiles fail to work on macOS after #107. A libsdl2 error is raised.

**To Reproduce**
Steps to reproduce the behaviour:
0. Try this on macOS Sonoma 
1. Compile any code using Makefiles like `4_cv_basics/1_image_representation/Makefile`.
2. Get `main.cpp:28:10: fatal error: 'SDL2/SDL.h' file not found`

**Expected behavior**
The file should have compiled successfully to give an executable.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS

### PR DESCRIPTION
**Pull request by Ritika128**
Updated 4_cv_basics/1_image_representation/Makefile
Updated 4_cv_basics/2_playing_with_images/Makefile

Fixes Issue #117 

Updated 4_cv_basics/3_interpolation/README.md

### CODE REVIEW

File: 4_cv_basics/1_image_representation/Makefile [hunk 1]
```diff
@@ -5,9 +5,9 @@ CC = g++
 PROJECT = image_representation		
 
 # Here Include specifies which directories can be added in the include path of the main.cpp
-CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) -Iinclude/		
+CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) $(shell pkg-config --cflags sdl2)
```
Comment (aPR0T0) [inline 4_cv_basics/1_image_representation/Makefile:8]: were cflags necessary for sdl2?
didn't it work without them?

File: 4_cv_basics/1_image_representation/Makefile [hunk 2]
```diff
@@ -5,9 +5,9 @@ CC = g++
 PROJECT = image_representation		
 
 # Here Include specifies which directories can be added in the include path of the main.cpp
-CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) -Iinclude/		
+CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) $(shell pkg-config --cflags sdl2)		
 # What libraries to be imported here it is opencv and SDL
-LIBS = $(shell pkg-config --libs opencv4) -lSDL2
+LIBS = $(shell pkg-config --libs opencv4) $(shell pkg-config --libs sdl2)
```
Comment (aPR0T0) [inline 4_cv_basics/1_image_representation/Makefile:10]: Looks good

File: 4_cv_basics/2_playing_with_images/Makefile [hunk 3]
```diff
@@ -5,9 +5,9 @@ CC = g++
 PROJECT = playing_with_images		
 
 # Here Include specifies which directories can be added in the include path of the main.cpp
-CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) -Iinclude/		
+CFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4) $(shell pkg-config --cflags sdl2)
```
Comment (aPR0T0) [inline 4_cv_basics/2_playing_with_images/Makefile:8]: Same here, were cflags necessary here?

**Review by aPR0T0 — CHANGES_REQUESTED** [review]
Just let me know, whether it works without the cflags of sdl2?
Because I have tested it in codespace and it works just fine

File: 4_cv_basics/1_image_representation/Makefile (hunk 1 above)
Comment (Ritika128) [reply 4_cv_basics/1_image_representation/Makefile:8]: no it's not working without --cflags sdl2

File: 4_cv_basics/2_playing_with_images/Makefile (hunk 3 above)
Comment (AryanNanda17) [reply 4_cv_basics/2_playing_with_images/Makefile:8]: Here the cflags is not necessary since we are not using the sdl2 library in this folder's code.

File: 4_cv_basics/1_image_representation/Makefile (hunk 1 above)
Comment (aPR0T0) [reply 4_cv_basics/1_image_representation/Makefile:8]: Then why did it work before in linux? As there was no cflag before

Comment (SuperChamp234) [reply 4_cv_basics/1_image_representation/Makefile:8]: It does not work because the directory structure is slightly different in macOS, therefore giving an error for `SDL2/SDL.h`

Comment (aPR0T0) [reply 4_cv_basics/1_image_representation/Makefile:8]: > It does not work because the directory structure is slightly different in macOS, therefore giving an error for `SDL2/SDL.h`

Sure, got it!

File: 4_cv_basics/2_playing_with_images/Makefile (hunk 3 above)
Comment (aPR0T0) [reply 4_cv_basics/2_playing_with_images/Makefile:8]: > Here, the cflags is not necessary since we are not using the sdl2 library in this folder's code.

@Ritika128 make the necessary changes in the next commit

File: 4_cv_basics/1_image_representation/Makefile (hunk 1 above)
Comment (aPR0T0) [reply 4_cv_basics/1_image_representation/Makefile:8]: I think then this change is good to go
