### ISSUE TITLE
Makefiles don’t work on macOS

### ISSUE THREAD

**Issue by SuperChamp234** [SRA-VJTI/Pixels_Seminar#117]
**Describe the bug**
Makefiles fail to work on macOS after #107. A libsdl2 error is raised.

**To Reproduce**
Steps to reproduce the behaviour:
0. Try this on macOS Sonoma 
1. Compile any code using Makefiles like `4_cv_basics/1_image_representation/Makefile`.
2. Get `main.cpp:28:10: fatal error: 'SDL2/SDL.h' file not found`

**Expected behavior**
The file should have compiled successfully to give an executable.

**Screenshots**
<img width="682" alt="image" src="https://github.com/SRA-VJTI/Pixels_Seminar/assets/40035606/212b7e50-68f1-4c1d-b7fd-597ff1c0e952">

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by Ritika128** [comment]
I'll work on this issue

**Comment by AryanNanda17** [comment]
@aPR0T0, you may also close this issue.
